/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.ConvertShoesToObject;
import com.shoes;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Lenovo
 */
public class FormDataShoes extends javax.swing.JFrame {

    /**
     * Creates new form FormDataShoes
     */
    public FormDataShoes() {
        initComponents();
        setDataShoes();
        GetCat();
    }
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;

    private void setDataShoes() {
        ConvertShoesToObject cvto = new ConvertShoesToObject();
        String[][] dataShoes = cvto.getShoes();
        tblShoes.setModel(new javax.swing.table.DefaultTableModel(
                dataShoes,
                new String[]{
                    "SHOE ID", "Name", "Category", "Type", "Quantity", "Price"
                }
        ));
        jScrollPaneShoes.setViewportView(tblShoes);

    }

    public void GetCat() {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/myshoesstoreoop");
            St = Con.createStatement();
            String query = "Select * from category";
            Rs = St.executeQuery(query);
            while (Rs.next()) {
                String Mycat = Rs.getString("name");
                Catcb.addItem(Mycat);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPaneShoes = new javax.swing.JScrollPane();
        tblShoes = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BtnAddShoes = new javax.swing.JButton();
        BtnEditShoes = new javax.swing.JButton();
        BtnDelShoes = new javax.swing.JButton();
        BtnClearShoes = new javax.swing.JButton();
        txtShoesId = new javax.swing.JTextField();
        txtShoesName = new javax.swing.JTextField();
        txtShoesPrice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Typecb = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Catcb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblShoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Type", "Quantity", "Price"
            }
        ));
        tblShoes.setRowHeight(30);
        tblShoes.setRowMargin(1);
        tblShoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblShoesMouseClicked(evt);
            }
        });
        jScrollPaneShoes.setViewportView(tblShoes);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("SHOE ID");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("NAME");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("TYPE");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("PRICE");

        BtnAddShoes.setBackground(new java.awt.Color(204, 102, 0));
        BtnAddShoes.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        BtnAddShoes.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddShoes.setText("ADD");
        BtnAddShoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAddShoesMouseClicked(evt);
            }
        });
        BtnAddShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddShoesActionPerformed(evt);
            }
        });

        BtnEditShoes.setBackground(new java.awt.Color(204, 102, 0));
        BtnEditShoes.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        BtnEditShoes.setForeground(new java.awt.Color(255, 255, 255));
        BtnEditShoes.setText("EDIT");
        BtnEditShoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEditShoesMouseClicked(evt);
            }
        });
        BtnEditShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditShoesActionPerformed(evt);
            }
        });

        BtnDelShoes.setBackground(new java.awt.Color(204, 102, 0));
        BtnDelShoes.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        BtnDelShoes.setForeground(new java.awt.Color(255, 255, 255));
        BtnDelShoes.setText("DELETE");
        BtnDelShoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDelShoesMouseClicked(evt);
            }
        });
        BtnDelShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelShoesActionPerformed(evt);
            }
        });

        BtnClearShoes.setBackground(new java.awt.Color(204, 102, 0));
        BtnClearShoes.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        BtnClearShoes.setForeground(new java.awt.Color(255, 255, 255));
        BtnClearShoes.setText("CLEAR");
        BtnClearShoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnClearShoesMouseClicked(evt);
            }
        });
        BtnClearShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearShoesActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("SHOES LIST");

        Typecb.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        Typecb.setForeground(new java.awt.Color(255, 102, 0));
        Typecb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High", "Low" }));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setText("MANAGE SHOES");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("QUANTITY");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("CATEGORY");

        Catcb.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        Catcb.setForeground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(435, 435, 435))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneShoes))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(283, 283, 283)
                                .addComponent(BtnAddShoes)
                                .addGap(50, 50, 50)
                                .addComponent(BtnEditShoes)
                                .addGap(53, 53, 53)
                                .addComponent(BtnDelShoes)
                                .addGap(27, 27, 27)
                                .addComponent(BtnClearShoes))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtShoesName, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtShoesId, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(109, 109, 109)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Catcb, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtShoesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Typecb, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(469, 469, 469)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtShoesId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtShoesName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(Catcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Typecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtShoesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAddShoes)
                    .addComponent(BtnClearShoes)
                    .addComponent(BtnDelShoes)
                    .addComponent(BtnEditShoes))
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneShoes, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/categories.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/seller.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-logout-60 (1).png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setText("X");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddShoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAddShoesActionPerformed

    private void BtnEditShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditShoesActionPerformed

    }//GEN-LAST:event_BtnEditShoesActionPerformed

    private void BtnDelShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelShoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDelShoesActionPerformed

    private void BtnClearShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearShoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnClearShoesActionPerformed

    private void tblShoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblShoesMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblShoes.getModel();
        int Myindex = tblShoes.getSelectedRow();
        txtShoesId.setText(model.getValueAt(Myindex, 0).toString());
        txtShoesName.setText(model.getValueAt(Myindex, 1).toString());
        Catcb.setSelectedItem(model.getValueAt(Myindex, 2).toString());
        Typecb.setSelectedItem(model.getValueAt(Myindex, 3).toString());
        txtQty.setText(model.getValueAt(Myindex, 4).toString());
        txtShoesPrice.setText(model.getValueAt(Myindex, 5).toString());
    }//GEN-LAST:event_tblShoesMouseClicked

    private void BtnAddShoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddShoesMouseClicked
        if (txtShoesId.getText().isEmpty() || txtShoesName.getText().isEmpty() || txtShoesPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            String id_shoes = txtShoesId.getText();
            String name = txtShoesName.getText();
            String category = Catcb.getSelectedItem().toString();
            String type = Typecb.getSelectedItem().toString();
            String strQuantity = txtQty.getText();
            int quantity = Integer.parseInt(strQuantity);
            String strPrice = txtShoesPrice.getText();
            int price = Integer.parseInt(strPrice);
            shoes shs = new shoes(id_shoes, name, category, type, quantity, price);
            exec.ExecuteShoes eShoes = new exec.ExecuteShoes();
            int hasil = eShoes.insertData(shs);
            if (hasil > 0) {
                JOptionPane.showMessageDialog(null, "Product Added Successfully");
                setDataShoes();
            } else {
                JOptionPane.showMessageDialog(null, "Product Added Failed");
            }
        }
    }//GEN-LAST:event_BtnAddShoesMouseClicked

    private void BtnDelShoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDelShoesMouseClicked
        if (txtShoesId.getText().isEmpty() || txtShoesName.getText().isEmpty() || txtShoesPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            String id_shoes = txtShoesId.getText();
            exec.ExecuteShoes eShoes = new exec.ExecuteShoes();
            int hasil = eShoes.deleteData(id_shoes);
            if (hasil > 0) {
                JOptionPane.showMessageDialog(null, "Product Deleted Successfully");
                setDataShoes();
            } else {
                JOptionPane.showMessageDialog(null, "Product Deleted Failed");
            }
        }
    }//GEN-LAST:event_BtnDelShoesMouseClicked

    private void BtnEditShoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditShoesMouseClicked
        if (txtShoesId.getText().isEmpty() || txtShoesName.getText().isEmpty() || txtShoesPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            String id_shoes = txtShoesId.getText();
            String name = txtShoesName.getText();
            String category = Catcb.getSelectedItem().toString();
            String type = Typecb.getSelectedItem().toString();
            String strQuantity = txtQty.getText();
            int quantity = Integer.parseInt(strQuantity);
            String strPrice = txtShoesPrice.getText();
            int price = Integer.parseInt(strPrice);

            shoes shs = new shoes(id_shoes, name, category, type, quantity, price);
            exec.ExecuteShoes eShoes = new exec.ExecuteShoes();
            int hasil = eShoes.editData(shs);
            if (hasil > 0) {
                JOptionPane.showMessageDialog(null, "Product Updated Successfully");
                setDataShoes();
            } else {
                JOptionPane.showMessageDialog(null, "Product Updated Failed");
            }
        }
    }//GEN-LAST:event_BtnEditShoesMouseClicked

    private void BtnClearShoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnClearShoesMouseClicked
        txtShoesId.setText("");
        txtShoesName.setText("");
        txtShoesPrice.setText("");
    }//GEN-LAST:event_BtnClearShoesMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new FormDataCategory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new FormDataSeller().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new FormDataLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDataShoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDataShoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDataShoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDataShoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDataShoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddShoes;
    private javax.swing.JButton BtnClearShoes;
    private javax.swing.JButton BtnDelShoes;
    private javax.swing.JButton BtnEditShoes;
    private javax.swing.JComboBox<String> Catcb;
    private javax.swing.JComboBox<String> Typecb;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneShoes;
    private javax.swing.JTable tblShoes;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtShoesId;
    private javax.swing.JTextField txtShoesName;
    private javax.swing.JTextField txtShoesPrice;
    // End of variables declaration//GEN-END:variables
}
