/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.ConvertCategoryToObject;
import com.ConvertShoesToObject;
import com.category;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class FormDataCategory extends javax.swing.JFrame {

    /**
     * Creates new form FormDataCategory
     */
    public FormDataCategory() {
        initComponents();
        setDataCategory();
    }

    private void setDataCategory() {
        ConvertCategoryToObject ccto = new ConvertCategoryToObject();
        String[][] dataCategory = ccto.getCategory();
        tblCategory.setModel(new javax.swing.table.DefaultTableModel(
                dataCategory,
                new String[]{
                    "Category ID", "Name", "Description"
                }
        ));
        jScrollPaneCategory.setViewportView(tblCategory);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPaneCategory = new javax.swing.JScrollPane();
        tblCategory = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BtnAddCategory = new javax.swing.JButton();
        BtnEditCategory = new javax.swing.JButton();
        BtnDelCategory = new javax.swing.JButton();
        BtnClearCategory = new javax.swing.JButton();
        txtCatId = new javax.swing.JTextField();
        txtCatName = new javax.swing.JTextField();
        txtCatDesc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tblCategory.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tblCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Description"
            }
        ));
        tblCategory.setRowHeight(30);
        tblCategory.setRowMargin(1);
        tblCategory.setSelectionBackground(new java.awt.Color(255, 204, 51));
        tblCategory.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoryMouseClicked(evt);
            }
        });
        jScrollPaneCategory.setViewportView(tblCategory);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("CATEGORY ID");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("NAME");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("DESCRIPTION");

        BtnAddCategory.setBackground(new java.awt.Color(204, 102, 0));
        BtnAddCategory.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        BtnAddCategory.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddCategory.setText("ADD");
        BtnAddCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAddCategoryMouseClicked(evt);
            }
        });
        BtnAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddCategoryActionPerformed(evt);
            }
        });

        BtnEditCategory.setBackground(new java.awt.Color(204, 102, 0));
        BtnEditCategory.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        BtnEditCategory.setForeground(new java.awt.Color(255, 255, 255));
        BtnEditCategory.setText("EDIT");
        BtnEditCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEditCategoryMouseClicked(evt);
            }
        });
        BtnEditCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditCategoryActionPerformed(evt);
            }
        });

        BtnDelCategory.setBackground(new java.awt.Color(204, 102, 0));
        BtnDelCategory.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        BtnDelCategory.setForeground(new java.awt.Color(255, 255, 255));
        BtnDelCategory.setText("DELETE");
        BtnDelCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDelCategoryMouseClicked(evt);
            }
        });
        BtnDelCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelCategoryActionPerformed(evt);
            }
        });

        BtnClearCategory.setBackground(new java.awt.Color(204, 102, 0));
        BtnClearCategory.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        BtnClearCategory.setForeground(new java.awt.Color(255, 255, 255));
        BtnClearCategory.setText("CLEAR");
        BtnClearCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnClearCategoryMouseClicked(evt);
            }
        });
        BtnClearCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearCategoryActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("CATEGORIES LIST");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setText("MANAGE CATEGORY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneCategory)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCatId, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCatName, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCatDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 165, Short.MAX_VALUE)
                        .addComponent(BtnAddCategory)
                        .addGap(50, 50, 50)
                        .addComponent(BtnEditCategory)
                        .addGap(53, 53, 53)
                        .addComponent(BtnDelCategory)
                        .addGap(27, 27, 27)
                        .addComponent(BtnClearCategory)
                        .addGap(293, 293, 293))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(397, 397, 397))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(435, 435, 435)
                    .addComponent(jLabel13)
                    .addContainerGap(436, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtCatId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtCatDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAddCategory)
                    .addComponent(BtnClearCategory)
                    .addComponent(BtnDelCategory)
                    .addComponent(BtnEditCategory))
                .addGap(71, 71, 71)
                .addComponent(jScrollPaneCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(312, 312, 312)
                    .addComponent(jLabel13)
                    .addContainerGap(313, Short.MAX_VALUE)))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sport-shoe.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-logout-60 (1).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/seller.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setText("X");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoryMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblCategory.getModel();
        int Myindex = tblCategory.getSelectedRow();
        txtCatId.setText(model.getValueAt(Myindex, 0).toString());
        txtCatName.setText(model.getValueAt(Myindex, 1).toString());
        txtCatDesc.setText(model.getValueAt(Myindex, 2).toString());

    }//GEN-LAST:event_tblCategoryMouseClicked

    private void BtnAddCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddCategoryMouseClicked
        if (txtCatId.getText().isEmpty() || txtCatName.getText().isEmpty() || txtCatDesc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            String id_category = txtCatId.getText();
            String name = txtCatName.getText();
            String description = txtCatDesc.getText();

            category ctr = new category(id_category, name, description);
            exec.ExecuteCategory eCategory = new exec.ExecuteCategory();
            int hasil = eCategory.insertData(ctr);
            if (hasil > 0) {
                JOptionPane.showMessageDialog(null, "Category Added Successfully");
                setDataCategory();
            } else {
                JOptionPane.showMessageDialog(null, "Category Added Failed");
            }
        }


    }//GEN-LAST:event_BtnAddCategoryMouseClicked

    private void BtnAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAddCategoryActionPerformed

    private void BtnEditCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditCategoryMouseClicked
        if (txtCatId.getText().isEmpty() || txtCatName.getText().isEmpty() || txtCatDesc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            String id_category = txtCatId.getText();
            String name = txtCatName.getText();
            String description = txtCatDesc.getText();

            category ctr = new category(id_category, name, description);
            exec.ExecuteCategory eCategory = new exec.ExecuteCategory();
            int hasil = eCategory.editData(ctr);
            if (hasil > 0) {
                JOptionPane.showMessageDialog(null, "Category Updated Successfully");
                setDataCategory();
            } else {
                JOptionPane.showMessageDialog(null, "Category Updated Failed");
            }
        }

    }//GEN-LAST:event_BtnEditCategoryMouseClicked

    private void BtnEditCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditCategoryActionPerformed

    }//GEN-LAST:event_BtnEditCategoryActionPerformed

    private void BtnDelCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDelCategoryMouseClicked
        if (txtCatId.getText().isEmpty() || txtCatName.getText().isEmpty() || txtCatDesc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            String id_category = txtCatId.getText();
            exec.ExecuteCategory eCategory = new exec.ExecuteCategory();
            int hasil = eCategory.deleteData(id_category);
            if (hasil > 0) {
                JOptionPane.showMessageDialog(null, "Category Deleted Successfully");
                setDataCategory();
            } else {
                JOptionPane.showMessageDialog(null, "Category Deleted Failed");
            }
        }
    }//GEN-LAST:event_BtnDelCategoryMouseClicked

    private void BtnDelCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDelCategoryActionPerformed

    private void BtnClearCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnClearCategoryActionPerformed

    private void BtnClearCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnClearCategoryMouseClicked
        txtCatId.setText("");
        txtCatName.setText("");
        txtCatDesc.setText("");
    }//GEN-LAST:event_BtnClearCategoryMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new FormDataShoes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new FormDataLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new FormDataSeller().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDataCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDataCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDataCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDataCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDataCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddCategory;
    private javax.swing.JButton BtnClearCategory;
    private javax.swing.JButton BtnDelCategory;
    private javax.swing.JButton BtnEditCategory;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPaneCategory;
    private javax.swing.JTable tblCategory;
    private javax.swing.JTextField txtCatDesc;
    private javax.swing.JTextField txtCatId;
    private javax.swing.JTextField txtCatName;
    // End of variables declaration//GEN-END:variables
}
